services:
  - type: web
    name: coursely-lms
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Coursely LMS"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: coursely-lms
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: coursely-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: coursely-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: coursely-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: coursely-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: coursely-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: BROADCAST_DRIVER
        value: log
      - key: MAIL_MAILER
        value: smtp
      - key: AWS_DEFAULT_REGION
        value: us-west-1
      - key: PUSHER_APP_CLUSTER
        value: mt1
    autoDeploy: false

databases:
  - name: coursely-db
    databaseName: coursely_lms
    user: coursely_user
    plan: starter